name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install node v16
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 16
        check-latest: true
    - name: Install latest npm
      run: |
        npm install -g npm@latest
    - name: Install dependencies
      run: |
        npm -v && npm ci
    - name: Run eslint
      run: npm run lint
  build:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - name: Install latest npm
        run: |
          npm install -g npm@latest
      - name: Install backend as module
        run: |
          npm install https://github.com/sogebot/sogeBot
      - name: Install dependencies
        run: |
          npm -v && npm ci
      - name: Run build
        run: npm run build