name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v14
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 14
        check-latest: true
    - name: Install latest npm
      run: |
        npm install -g npm@latest
    - name: Install dependencies
      run: |
        npm -v && npm ci
    - name: Run eslint
      run: npm run lint
  build:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
      - name: Install latest npm
        run: |
          npm install -g npm@latest
      - name: Install dependencies
        run: |
          npm -v && npm ci
      - name: Run build
        run: npm run build